[tools]
flux2 = "2.7.5"
talosctl = "latest"
"aqua:helm/helm" = "latest"
tmux = "latest"
"aqua:fish-shell/fish-shell" = "latest"
"aqua:abiosoft/colima" = "latest"
"aqua:docker/compose" = "latest"
kubectl = "latest"
"aqua:anomalyco/opencode" = "latest"
