[tools]
chezmoi = "2.70.0"
flux2 = "2.7.5"
talosctl = "latest"
"aqua:helm/helm" = "latest"
tmux = "latest"
"aqua:fish-shell/fish-shell" = "latest"
"aqua:abiosoft/colima" = "latest"
"aqua:docker/compose" = "latest"

