APPLICATION=$1
CONFIG_PATH=$2
FILE_NAME=$3
mkdir -p $CONFIG_PATH
[ -f $CONFIG_PATH/$FILE_NAME ] && mv $CONFIG_PATH/$FILE_NAME $CONFIG_PATH/$FILE_NAME.backup
ln -s ~/projects/dotfiles/config/$APPLICATION/$FILE_NAME $CONFIG_PATH/$FILE_NAME
