. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/completions/asdf.bash"
. "$HOME/projects/dotfiles/zsh/prompt
. <(flux completion zsh)

PATH="/opt/homebrew/bin:$PATH"
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
