. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/completions/asdf.bash"
source ~/powerlevel10k/powerlevel10k.zsh-theme
PATH="/opt/homebrew/bin:$PATH"
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

. <(flux completion zsh)